# Generated by Django 5.0.2 on 2025-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
