# Generated by Django 5.0.14 on 2025-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='disease',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='cause',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10),
        ),
    ]
