# Generated by Django 5.2.4 on 2025-07-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_doctorname'),
        ('donor', '0003_remove_blooddonate_disease_blooddonate_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
