# Generated by Django 5.0.14 on 2025-07-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_blooddonate_donor'),
        ('donor', '0005_data_migrate_donor_to_profile'),
    ]

    operations = [
    ]
