# Generated by Django 5.2.4 on 2025-07-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_cleanup_orphaned_blooddonate'),
        ('donor', '0006_merge_20250711_1323'),
    ]

    operations = [
    ]
