# Generated by Django 5.0.14 on 2025-07-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_merge_20250711_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonate',
            old_name='cause',
            new_name='diseases',
        ),
    ]
