# Generated by Django 5.2.4 on 2025-07-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_age_profile_cause_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctorname',
        ),
    ]
