# Generated by Django 5.0.14 on 2025-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.AddField(
            model_name='patient',
            name='cause',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
