# Generated by Django 5.2.4 on 2025-07-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_doctorname'),
        ('blood', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_donor',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_patient',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
