# Generated by Django 5.0.14 on 2025-07-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_doctorname'),
        ('blood', '0003_remove_bloodrequest_request_by_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='bloodgroup',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='recipient_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
