# Generated by Django 5.0.14 on 2025-07-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_remove_bloodrequest_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_phone_verified',
            new_name='is_verified',
        ),
    ]
